Repository svthalia/concrexit, pull requests merged in 2020-03, with the labels that each got.

#901 Add GitHub release drafter actions
  .github/release-drafter.yaml
  .github/workflows/release-drafter.yaml
Labels: technical change

#2 Migrate from Gitlab CI to GitHub Actions
  .github/release-drafter.yaml
  .github/workflows/build-dependencies-docker.yaml
  .github/workflows/build-production-docker.yaml
  .github/workflows/new-pull-request.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/review.yaml
  .github/workflows/test.yaml
  .gitlab-ci.yml
  resources/continuous-integration/config/build.yaml
  resources/continuous-integration/config/deploy-review.yaml
  resources/continuous-integration/config/deploy-static-sites.yaml
  resources/continuous-integration/config/test.yaml
  resources/continuous-integration/review/review-host-create.sh
  resources/continuous-integration/review/review-host-remove.sh
  website/thaliawebsite/settings/__init__.py
  website/thaliawebsite/settings/testing.py
Labels: technical change

#3 Replace GitLab repo templates by GitHub equivalents
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/technical-change.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitlab/issue_templates/Bug.md
  .gitlab/issue_templates/Feature Request.md
  .gitlab/issue_templates/Technical Change Request.md
  .gitlab/merge_request_templates/Added New Feature.md
  .gitlab/merge_request_templates/Implemented Technical Change.md
  .gitlab/merge_request_templates/Resolved Bug.md
Labels: technical change

#1042 Set review environment AWS variables
  .github/workflows/review.yaml
Labels: technical change

#1036 Fix public events calendarjs API
  website/events/api/serializers.py
Labels: bug, events

#1045 Add checkout to review remove job
  .github/workflows/review.yaml
Labels: technical change

#900 Add GitHub labeler
  .editorconfig
  .github/app-labeler.yaml
  .github/release-drafter.yaml
  .github/type-labeler.yaml
  .github/workflows/labeler.yaml
Labels: technical change

#1041 Replace all GitLab references in code with GitHub
  README.md
  release.sh
  website/payments/templates/payments/bankaccount_list.html
  website/thaliawebsite/templates/base.html
Labels: technical change

#1047 Add more issue types
  .github/ISSUE_TEMPLATE/other.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/app-labeler.yaml
  .github/release-drafter.yaml
  .github/type-labeler.yaml
  .github/workflows/build-dependencies-docker.yaml
  .github/workflows/new-pull-request.yaml
  .github/workflows/test.yaml
Labels: technical change

#1050 Replace thaliawww GitHub organisation by svthalia
  README.md
  website/payments/templates/payments/bankaccount_list.html
  website/thaliawebsite/templates/base.html
Labels: chore

#1051 Add skip-changelog to release drafter
  .editorconfig
  .github/release-drafter.yaml
Labels: chore, skip-changelog

#1035 Delete payments when Payment.NONE in pizzas
  website/events/services.py
  website/payments/services.py
  website/payments/tests/test_services.py
  website/pizzas/api/serializers.py
  website/pizzas/api/viewsets.py
  website/pizzas/migrations/0012_auto_20191116_2329.py
  website/pizzas/models.py
  website/pizzas/signals.py
  website/pizzas/templates/pizzas/admin/orders.html
  website/pizzas/views.py
Labels: chore, events, payments, pizzas

#1057 Fix the focus color of a dropdown nav-item
  website/thaliawebsite/static/css/base.scss
Labels: bug

#1055 Move user menu to dropdown instead of page
  website/members/templates/members/user/index.html
  website/members/urls.py
  website/members/views.py
  website/thaliawebsite/static/css/base.scss
  website/thaliawebsite/templates/base.html
Labels: feature, members

#1060 Change partner banner filters
  website/partners/static/partners/css/style.scss
  website/partners/templates/partners/banners.html
Labels: feature, partners

#1061 Refactor events models to separate files
  docs/events.models.rst
  docs/events.rst
  website/events/admin.py
  website/events/admin_views.py
  website/events/api/serializers.py
  website/events/api/viewsets.py
  website/events/emails.py
  website/events/forms.py
  website/events/locale/nl/LC_MESSAGES/django.mo
  website/events/locale/nl/LC_MESSAGES/django.po
  website/events/migrations/0040_auto_20200329_2341.py
  website/events/models/__init__.py
  website/events/models/event.py
  website/events/models/event_registration.py
  website/events/models/feed_token.py
  website/events/models/registration_information_field.py
  website/events/services.py
  website/events/templates/events/admin/registrations_table.html
  website/events/tests/test_admin.py
  website/events/tests/test_api.py
  website/events/tests/test_models.py
  website/events/tests/test_services.py
  website/events/tests/test_views.py
  website/events/views.py
  website/pizzas/signals.py
Labels: events, refactor
