Repository svthalia/concrexit, pull requests merged in 2023-12, with the labels that each got.

#3467 Promo Request status updates for organisers
  website/promotion/apps.py
  website/promotion/emails.py
  website/promotion/migrations/0005_promotionrequest_status_updated.py
  website/promotion/models.py
  website/promotion/signals.py
  website/promotion/tasks.py
  website/promotion/templates/promotion/email/daily_update_overview.html
  website/promotion/templates/promotion/email/daily_update_overview.txt
  website/promotion/templates/promotion/email/status_update.txt
  website/promotion/templates/promotion/email/weekly_overview.html
  website/thaliawebsite/settings.py
Labels: feature

#3423 Add events.view_unpublished permission
  website/events/admin/event.py
  website/events/api/calendarjs/permissions.py
  website/events/api/calendarjs/views.py
  website/events/migrations/0069_alter_event_options.py
  website/events/models/event.py
  website/events/templates/events/index.html
  website/events/tests/test_admin.py
Labels: app:events, feature

#3420 Overhaul registrations
  website/payments/services.py
  website/registrations/README.md
  website/registrations/README.rst
  website/registrations/admin.py
  website/registrations/forms.py
  website/registrations/migrations/0031_alter_entry_length.py
  website/registrations/models.py
  website/registrations/payables.py
  website/registrations/services.py
  website/registrations/signals.py
  website/registrations/templates/registrations/register_member.html
  website/registrations/tests/test_admin.py
  website/registrations/tests/test_forms.py
  website/registrations/tests/test_models.py
  website/registrations/tests/test_payables.py
  website/registrations/tests/test_services.py
  website/registrations/tests/test_signals.py
  website/registrations/tests/test_views.py
  website/registrations/views.py
Labels: app:registrations, bug, chore

#3525 Synchronize moneybird contacts at night
  website/moneybirdsynchronization/migrations/0008_moneybirdcontact_needs_synchronization.py
  website/moneybirdsynchronization/models.py
  website/moneybirdsynchronization/services.py
  website/moneybirdsynchronization/signals.py
  website/moneybirdsynchronization/tests/test_services.py
Labels: feature, app:moneybirdsynchronization

#3482 Fix alumni mailinglist missing people
  website/mailinglists/services.py
  website/members/forms.py
  website/members/migrations/0048_auto_20231121_2025.py
  website/registrations/services.py
Labels: app:mailinglists, bug

#3500 Push notification queue app
  website/events/emails.py
  website/events/services.py
  website/events/signals.py
  website/events/tests/test_services.py
  website/pushnotifications/signals/events.py
Labels: app:events, feature, app:pushnotifications

#3530 Update responsible disclosure policy
  infra/nginx/concrexit.conf.template
  infra/nginx/resources/pgp-key.txt
  infra/nginx/resources/security.txt
  website/singlepages/templates/singlepages/responsible_disclosure.html
Labels: chore

#3547 Fix HTML markup in tooltip
  website/payments/templates/payments/templatetags/payment_button.html
Labels: bug

#3548 Fix BIC validation
  website/payments/models.py
Labels: bug

#3543 Fix moneybird sync skipping invoice creation
  website/events/models/event_registration.py
  website/moneybirdsynchronization/services.py
Labels: bug

#3531 Fix 500 on invalid registration ID url
  website/registrations/admin.py
  website/registrations/tests/test_admin.py
Labels: bug

#3549 Fix empty cancellations table layout
  website/events/static/events/js/admin.js
Labels: bug
