Repository svthalia/concrexit, pull requests merged in 2024-11, with the labels that each got.

#3827 Disabled js i18n API
  website/events/static/events/js/listview.js
  website/events/static/events/js/main.js
  website/pizzas/static/pizzas/js/admin.js
  website/registrations/static/admin/registrations/js/registrations.js
  website/thaliawebsite/settings.py
  website/thaliawebsite/templates/base.html
  website/thaliawebsite/urls.py
Labels: chore

#3829 Bug: Override BaseUserAdmin add_fieldsets
  website/members/admin.py
Labels: bug

#3729 Add check if people are still studying
  website/members/apps.py
  website/members/emails.py
  website/members/fixtures/members.json
  website/members/migrations/0050_membership_study_long.py
  website/members/migrations/0051_membership_study_long_until.py
  website/members/models/membership.py
  website/members/services.py
  website/members/tasks.py
  website/members/templates/members/announcement_not_member.html
  website/members/templates/members/email/membership_announcement.html
  website/members/templates/members/email/membership_announcement.txt
  website/members/templates/members/email/membership_announcement_notification.html
  website/members/templates/members/email/membership_announcement_notification.txt
  website/members/templates/members/email/yearly_study_check.html
  website/members/templates/members/email/yearly_study_check.txt
  website/members/templates/members/email/yearly_study_check_reminder.html
  website/members/templates/members/email/yearly_study_check_reminder.txt
  website/members/tests/test_emails.py
  website/registrations/README.md
  website/registrations/forms.py
  website/registrations/services.py
  website/registrations/templates/registrations/new_year_renewal.html
  website/registrations/templates/registrations/renewal.html
  website/registrations/templates/registrations/renewal_studylong_success.html
  website/registrations/tests/test_forms.py
  website/registrations/tests/test_services.py
  website/registrations/tests/test_views.py
  website/registrations/urls.py
  website/registrations/views.py
  website/thaliawebsite/settings.py
  website/utils/management/commands/createfixtures.py
Labels: feature

#3848 Feature/study long to benefactor
  website/registrations/forms.py
  website/registrations/services.py
  website/registrations/templates/registrations/renewal.html
  website/registrations/tests/test_views.py
  website/registrations/views.py
Labels: feature

#3842 Changed the copyright year to be shown in hex
  website/thaliawebsite/context_processors.py
  website/thaliawebsite/settings.py
  website/thaliawebsite/templates/base.html
Labels: feature

#3853 remove make_random_password
  website/activemembers/gsuite.py
Labels: bug
