Repository svthalia/concrexit, pull requests merged in 2024-10, with the labels that each got.

#3775 Upgrade to Django 5.1
  poetry.lock
  pyproject.toml
  website/newsletters/services.py
  website/payments/tests/test_admin.py
  website/thaliawebsite/templates/paginated_page.html
  website/thaliawebsite/views.py
  website/utils/media/views.py
Labels: chore

#3816 Improve ical discoverability
  website/events/templates/events/ical_help.html
  website/events/templates/events/index.html
  website/events/urls.py
  website/events/views.py
  website/members/templates/members/email/welcome.html
  website/members/templates/members/email/welcome.txt
Labels: app:events, feature

#3820 Small improvements on statistics page
  website/members/services.py
  website/members/templates/members/statistics.html
  website/members/views.py
  website/pizzas/services.py
  website/sales/services.py
Labels: feature
