Repository svthalia/concrexit, pull requests merged in 2024-02, with the labels that each got.

#3607 fix alumni acounts not getting a contract because there not a member
  website/moneybirdsynchronization/models.py
Labels: priority: high, easy and fun, bug, app:moneybirdsynchronization

#3608 Disable crashing admin list filter facet counts
  website/activemembers/admin.py
  website/members/admin.py
  website/payments/admin.py
  website/sales/admin/order_admin.py
Labels: bug

#3616 Disable sentry cron monitoring
  website/thaliawebsite/settings.py
Labels: chore
