Repository svthalia/concrexit, pull requests merged in 2024-05, with the labels that each got.

#3649 Improve album upload error handling
  website/photos/admin.py
  website/photos/services.py
  website/photos/tasks.py
  website/photos/templates/photos/emails/upload-processed.txt
Labels: feature

#3682 Redirect to next or LOGIN_REDIRECT_URL after loggin in with django otp
  website/templates/two_factor/core/login.html
Labels: bug

#3684 Make newsletter deregistration warning more generic
  website/newsletters/templates/newsletters/email.html
Labels: feature

#3685 Fix sales admin autocomplete filters pk exact
  website/sales/admin/order_admin.py
Labels: bug

#3686 Add Thabloid API
  website/thabloid/api/__init__.py
  website/thabloid/api/v2/__init__.py
  website/thabloid/api/v2/serializers.py
  website/thabloid/api/v2/urls.py
  website/thabloid/api/v2/views.py
  website/thaliawebsite/api/v2/urls.py
  website/thaliawebsite/settings.py
Labels: feature

#3218 Add facedetection api endpoints
  website/facedetection/api/v2/__init__.py
  website/facedetection/api/v2/serializers.py
  website/facedetection/api/v2/urls.py
  website/facedetection/api/v2/views.py
  website/facedetection/services.py
  website/facedetection/views.py
  website/thaliawebsite/api/v2/urls.py
  website/thaliawebsite/settings.py
Labels: feature, api, app:facedetection
