Repository svthalia/concrexit, pull requests merged in 2024-06, with the labels that each got.

#3678 Timeout to registrations and renewals
  website/registrations/emails.py
  website/registrations/tasks.py
  website/registrations/templates/registrations/email/reminder_open_registration.html
  website/registrations/templates/registrations/email/reminder_open_registration.txt
  website/registrations/tests/test_emails.py
  website/thaliawebsite/settings.py
Labels: feature

#3692 Fix trying to delete already-deleted invoices from moneybird
  website/moneybirdsynchronization/services.py
Labels: bug

#3721 Fix weird colour filter widget headers
  website/thaliawebsite/templates/admin/base_site.html
Labels: bug

#3716 Handle 400 when archiving an already archived moneybird contact
  website/moneybirdsynchronization/administration.py
  website/moneybirdsynchronization/services.py
  website/moneybirdsynchronization/tests/test_services.py
Labels: bug

#3720 Fix check if you are allowed to order food
  website/events/templates/events/event.html
  website/pizzas/api/v2/views.py
  website/pizzas/templates/pizzas/index.html
  website/pizzas/views.py
Labels: bug

#3735 Fix crashing on documents of upcoming lecture year
  website/documents/views.py
Labels: app:documents, bug
